cat > sonar-project.properties << 'EOF'
sonar.projectKey=varshinirameshkumar_Secret_Sharer
sonar.organization=varshinirameshkumar

sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

sonar.language=java
sonar.sourceEncoding=UTF-8
EOF